apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legal-backend
  template:
    metadata:
      labels:
        app: legal-backend
    spec:
      containers:
      - name: backend
        image: legaldraft/backend:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: connection-string
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-credentials