version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://user:pass@db:5432/legaldraft
      JWT_SECRET: development-secret
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: legaldraft
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-service:
    build: ./ai-service
    command: uvicorn service.api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      MODEL_PATH: /app/model.onnx

volumes:
  pgdata: